[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "ipidea-client"
authors = [{name = "Pinclr Coders", email = "coding@pinclr.com"}]
dynamic = ["version", "description"]
