---
name: YAMLLint
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.yaml'
      - '**.yml'
jobs:
  lint:
    name: yamllint
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Run yamllint
        run: yamllint -s -c .yamllint.yaml .
